export interface NeighborhoodData {
  id: string;
  nameKey: string;
  gradientFrom: string;
  gradientTo: string;
  avgPrice: string;
  walkScore: number;
  transitScore: number;
  safetyRating: number;
  restaurants: number;
  schools: number;
  parks: number;
  shopping: number;
  propertyCount: number;
  bestForKeys: string[];
  insightKey: string;
  mapX: number;
  mapY: number;
  mapWidth: number;
  mapHeight: number;
}

export const neighborhoods: NeighborhoodData[] = [
  {
    id: "downtown",
    nameKey: "neighborhoodGuide.downtown",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$850K",
    walkScore: 92,
    transitScore: 88,
    safetyRating: 78,
    restaurants: 45,
    schools: 8,
    parks: 5,
    shopping: 32,
    propertyCount: 124,
    bestForKeys: ["neighborhoodGuide.youngProfessionals", "neighborhoodGuide.investors"],
    insightKey: "neighborhoodGuide.downtownInsight",
    mapX: 35,
    mapY: 40,
    mapWidth: 18,
    mapHeight: 14,
  },
  {
    id: "waterfront",
    nameKey: "neighborhoodGuide.waterfront",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$1.2M",
    walkScore: 85,
    transitScore: 72,
    safetyRating: 90,
    restaurants: 28,
    schools: 6,
    parks: 8,
    shopping: 18,
    propertyCount: 89,
    bestForKeys: ["neighborhoodGuide.retirees", "neighborhoodGuide.luxurySeekers"],
    insightKey: "neighborhoodGuide.waterfrontInsight",
    mapX: 58,
    mapY: 55,
    mapWidth: 20,
    mapHeight: 16,
  },
  {
    id: "suburbs",
    nameKey: "neighborhoodGuide.suburbs",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$450K",
    walkScore: 62,
    transitScore: 55,
    safetyRating: 92,
    restaurants: 15,
    schools: 18,
    parks: 12,
    shopping: 10,
    propertyCount: 256,
    bestForKeys: ["neighborhoodGuide.families", "neighborhoodGuide.petLovers"],
    insightKey: "neighborhoodGuide.suburbsInsight",
    mapX: 15,
    mapY: 65,
    mapWidth: 22,
    mapHeight: 18,
  },
  {
    id: "midtown",
    nameKey: "neighborhoodGuide.midtown",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$680K",
    walkScore: 88,
    transitScore: 82,
    safetyRating: 84,
    restaurants: 38,
    schools: 12,
    parks: 6,
    shopping: 25,
    propertyCount: 167,
    bestForKeys: ["neighborhoodGuide.youngProfessionals", "neighborhoodGuide.families"],
    insightKey: "neighborhoodGuide.midtownInsight",
    mapX: 42,
    mapY: 30,
    mapWidth: 16,
    mapHeight: 12,
  },
  {
    id: "eastside",
    nameKey: "neighborhoodGuide.eastside",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$520K",
    walkScore: 78,
    transitScore: 68,
    safetyRating: 86,
    restaurants: 22,
    schools: 14,
    parks: 9,
    shopping: 14,
    propertyCount: 198,
    bestForKeys: ["neighborhoodGuide.families", "neighborhoodGuide.firstTimeBuyers"],
    insightKey: "neighborhoodGuide.eastsideInsight",
    mapX: 72,
    mapY: 35,
    mapWidth: 18,
    mapHeight: 15,
  },
  {
    id: "westend",
    nameKey: "neighborhoodGuide.westend",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$790K",
    walkScore: 82,
    transitScore: 76,
    safetyRating: 88,
    restaurants: 30,
    schools: 10,
    parks: 7,
    shopping: 20,
    propertyCount: 145,
    bestForKeys: ["neighborhoodGuide.retirees", "neighborhoodGuide.luxurySeekers"],
    insightKey: "neighborhoodGuide.westendInsight",
    mapX: 12,
    mapY: 30,
    mapWidth: 17,
    mapHeight: 13,
  },
  {
    id: "northgate",
    nameKey: "neighborhoodGuide.northgate",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$380K",
    walkScore: 70,
    transitScore: 62,
    safetyRating: 82,
    restaurants: 18,
    schools: 16,
    parks: 10,
    shopping: 12,
    propertyCount: 312,
    bestForKeys: ["neighborhoodGuide.firstTimeBuyers", "neighborhoodGuide.investors"],
    insightKey: "neighborhoodGuide.northgateInsight",
    mapX: 38,
    mapY: 12,
    mapWidth: 20,
    mapHeight: 14,
  },
  {
    id: "southpark",
    nameKey: "neighborhoodGuide.southpark",
    gradientFrom: "",
    gradientTo: "",
    avgPrice: "$560K",
    walkScore: 74,
    transitScore: 70,
    safetyRating: 80,
    restaurants: 20,
    schools: 11,
    parks: 8,
    shopping: 16,
    propertyCount: 178,
    bestForKeys: ["neighborhoodGuide.petLovers", "neighborhoodGuide.families"],
    insightKey: "neighborhoodGuide.southparkInsight",
    mapX: 55,
    mapY: 75,
    mapWidth: 19,
    mapHeight: 14,
  },
];
